DATA:
  CLASS_NAME_FILE: 'configs/namefiles/coco80.names'
  AUGMENT: 1

  TRAIN:
    IMG_DIR: 'data/INRIAPerson/Train/pos'
    LAB_DIR:

DETECTOR:
  NAME: ["YOLOV5"]
  INPUT_SIZE: [416, 416]
  BATCH_SIZE: 8
  CONF_THRESH: 0.5
  IOU_THRESH: 0.45

  PERTURB:
    GATE: 'shakedrop'

ATTACKER:
  METHOD: "mim"
  EPSILON: 255
  MAX_EPOCH: 1000
  ITER_STEP: 5
  STEP_LR: 0.03
  ATTACK_CLASS: '0'
  LOSS_FUNC: "descend-mse" # [null, descend-mse, ascend-mse, obj, obj-tv]
  LR_SCHEDULER: 'ALRS'
  tv_eta: 2.5

  PATCH:
    WIDTH: 300
    HEIGHT: 300
    SCALE: 0.15
    INIT: "gray"
    TRANSFORM: ['jitter', 'median_pool', 'rotate', 'cutout']